// <auto-generated />
using System;
using FJMA20241103.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FJMA20241103.Migrations
{
    [DbContext(typeof(FJMA20241103DBContext))]
    [Migration("20240318220212_migra1")]
    partial class migra1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FJMA20241103.Models.Auto", b =>
                {
                    b.Property<int>("IdAuto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAuto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuto"), 1L, 1);

                    b.Property<int?>("Anio")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("anio");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modelo");

                    b.HasKey("IdAuto")
                        .HasName("PK__Autos__D8600DCF80AA0115");

                    b.ToTable("Autos");
                });

            modelBuilder.Entity("FJMA20241103.Models.ComponenteCarro", b =>
                {
                    b.Property<int>("IdComponente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idComponente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComponente"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdAuto")
                        .HasColumnType("int")
                        .HasColumnName("idAuto");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdComponente")
                        .HasName("PK__Componen__001F4C930631F843");

                    b.HasIndex("IdAuto");

                    b.ToTable("ComponenteCarro", (string)null);
                });

            modelBuilder.Entity("FJMA20241103.Models.ComponenteCarro", b =>
                {
                    b.HasOne("FJMA20241103.Models.Auto", "IdAutoNavigation")
                        .WithMany("ComponenteCarros")
                        .HasForeignKey("IdAuto")
                        .HasConstraintName("FK__Component__idAut__398D8EEE");

                    b.Navigation("IdAutoNavigation");
                });

            modelBuilder.Entity("FJMA20241103.Models.Auto", b =>
                {
                    b.Navigation("ComponenteCarros");
                });
#pragma warning restore 612, 618
        }
    }
}
